name: aspose_omr_cloud_sdk
version: 0.17.05
description: This SDK allows you to work with Aspose.OMR for Cloud REST APIs in your Dart or Flutter applications quickly and easily

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http: '>=0.13.0 <0.14.0'

dev_dependencies: 
  test: ^1.19.2 
 